version: '3.3'

services:

   postgres:
      image: 0f92610e9336
      
      #restart: always

      environment:
         - POSTGRES_USER=tesis
         - POSTGRES_PASSWORD=tesis
         - POSTGRES_DB=tesis
      ports:
         - 44:5432
      volumes:
         - ~/Desktop/appdocker/postgresdata:/var/lib/postgresql/data
   

   web:
      image: ac86b30a873b
      #build: ./envdjango
      command: python manage.py runserver 0.0.0.0:8000
      volumes:
         - ~/Desktop/codigostesis/appdocker/tesisweb:/usr/src/app
      ports:
         - 8282:8000
   
