version: '3.3'

services:

   postgres:
      image: 0f92610e9336
      
      #restart: always

      ports:
         - 44:5432
      volumes:
         - ~/Desktop/appdocker/postgresdata:/var/lib/postgresql/data
      env_file:
         - .env.postgres

   web:
      image: 842c5dfbc873
      #build: ./tesisweb
      #image: webdjango:v0.8
      #command: python manage.py runserver 0.0.0.0:8000
      command: gunicorn tesisweb.wsgi:application --bind 0.0.0.0:8000
      volumes:
         #- ~/Desktop/codigostesis/appdocker/tesisweb:/usr/src/app
         - ~/Desktop/codigostesis/appdocker/tesisweb:/home/app/web
         - ~/Desktop/appdocker/static_volume:/home/app/web/static
         - ~/Desktop/appdocker/media_volume:/home/app/web/media
      #ports:
         #- 8282:8000
      expose:
         - 8000
      env_file:
         - .env.web
      depends_on:
         - postgres
         
   nginx:
      image: 063fb952c08d
      volumes:
         - ~/Desktop/appdocker/static_volume:/home/app/web/static
         - ~/Desktop/appdocker/media_volume:/home/app/web/media
      ports:
         - 1010:80
      depends_on:
         - web
   
   
      
   
