version: '3.3'

services:
  
   facerecognition:
   
      stdin_open: true
      
      tty: true
      
      image: c1b77b70f7d1
      
      environment:
         - DISPLAY=unix$DISPLAY
      
      env_file:
         - .env.recognition
      
      volumes:
         - ~/Desktop/appdocker/recognition:/app
         - ~/Desktop/appdocker/media_volume/personas:/app/personas
         - /tmp/.X11-unix:/tmp/.X11-unix
         - /tmp/.docker.xauth:/tmp/.docker.xauth
         
      privileged: true
