version: '3.3'

services:
   
   postgres:
      image: 02da44b1d4a6

      environment:
         - POSTGRES_PASSWORD=postgres
      ports:
         - 4443:5432
      volumes:
         - ~/Desktop/app/postgresdata:/var/lib/postgresql/data
      restart: always
  
   facerecognition:
   
      stdin_open: true
      
      tty: true
      
      image: c1b77b70f7d1
      
      environment:
         - DISPLAY=unix$DISPLAY
      
      env_file:
         - .env.recognition
      
      volumes:
         - ~/Desktop/app:/app
         - /tmp/.X11-unix:/tmp/.X11-unix
         - /tmp/.docker.xauth:/tmp/.docker.xauth
         
      privileged: true
