FROM ubuntu:latest

WORKDIR dockerfacereco

COPY . .
RUN apt-get update
RUN apt-get install -y python3
RUN apt-get install -y nano
RUN apt-get install -y python3-pip
RUN DEBIAN_FRONTEND="noninteractive" TZ="America/Caracas" apt-get install -y --fix-missing \
    build-essential \
    cmake \
    gfortran \
    git \
    wget \
    curl \
    graphicsmagick \
    libgraphicsmagick1-dev \
    libatlas-base-dev \
    libavcodec-dev \
    libavformat-dev \
    libgtk2.0-dev \
    libjpeg-dev \
    liblapack-dev \
    libswscale-dev \
    pkg-config \
    python3-dev \
    software-properties-common \
    zip \
    && apt-get clean && rm -rf /tmp/* /var/tmp/*

RUN pip3 install --upgrade pip && \
    git clone -b 'v19.21' --single-branch https://github.com/davisking/dlib.git && \
    cd dlib/ && \
    python3 setup.py install --no USE_AVX_INSTRUCTIONS
RUN pip3 install face_recognition
RUN pip3 install mediapipe
RUN pip3 install opencv-contrib-python
RUN DEBIAN_FRONTEND="noninteractive" TZ="America/Caracas" apt-get install ffmpeg libsm6 libxext6  -y
CMD ["python3", "/dockerfacereco/face_detection_prueba_stream_parpadeos.py"]
