FROM ubuntu:latest

WORKDIR app

COPY . .
RUN apt-get update
RUN apt-get install -y python3
RUN apt-get install -y nano
RUN apt-get install -y python3-pip
RUN pip3 install tflite_runtime
RUN pip3 install mediapipe
RUN pip3 install opencv-contrib-python
RUN DEBIAN_FRONTEND="noninteractive" TZ="America/Caracas" apt-get install ffmpeg libsm6 libxext6  -y
ENV QT_DEBUG_PLUGINS=1
CMD ["python3", "/app/probar_modelos_tflite.py"]
