# Generated by Django 4.0.3 on 2022-03-20 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contratos',
            fields=[
                ('nombre', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='nombre del nuevo contrato')),
            ],
            options={
                'verbose_name_plural': 'Contratos',
            },
        ),
        migrations.CreateModel(
            name='diasdelasemana',
            fields=[
                ('dia', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'Dias de la semana',
            },
        ),
        migrations.CreateModel(
            name='usuarios',
            fields=[
                ('cedula', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrato', to='web.contratos', verbose_name='contratousuarios')),
            ],
            options={
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='interacciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('razon', models.CharField(max_length=20)),
                ('contrato', models.CharField(max_length=100)),
                ('cedula', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cedulainteracciones', to='web.usuarios')),
            ],
            options={
                'verbose_name_plural': 'Interacciones',
            },
        ),
        migrations.CreateModel(
            name='horariospermitidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrada', models.TimeField()),
                ('salida', models.TimeField()),
                ('cedula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ceduladiaspermitidos', to='web.usuarios')),
                ('dia', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='diasdelasemana', to='web.diasdelasemana')),
            ],
            options={
                'verbose_name_plural': 'Horarios',
            },
        ),
    ]
