# Generated by Django 4.0.2 on 2022-03-04 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='interacciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('cedula', models.IntegerField()),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('razon', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='oficina',
            fields=[
                ('cedula', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
    ]
