# Generated by Django 4.0.2 on 2022-03-08 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('postgrescrud', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='horariospermitidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(max_length=20)),
                ('entrada', models.TimeField()),
                ('salida', models.TimeField()),
                ('cedula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ceduladiaspermitidos', to='postgrescrud.usuarios')),
            ],
            options={
                'verbose_name_plural': 'Horarios',
            },
        ),
    ]
