# Generated by Django 4.0.2 on 2022-03-04 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postgrescrud', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interacciones',
            name='nombre',
        ),
    ]
