# Generated by Django 4.0.2 on 2022-03-08 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('postgrescrud', '0002_horariospermitidos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interacciones',
            name='cedula',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cedulainteracciones', to='postgrescrud.usuarios'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrato', to='postgrescrud.contratos', verbose_name='contratousuarios'),
        ),
    ]
