# Generated by Django 4.0.2 on 2022-03-04 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postgrescrud', '0002_remove_interacciones_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='interacciones',
            name='nombre',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
