# Generated by Django 4.0.2 on 2022-03-04 23:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('postgrescrud', '0004_remove_interacciones_fecha_remove_interacciones_hora_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interacciones',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interacciones',
            name='hora',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interacciones',
            name='nombre',
            field=models.CharField(default='abr', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interacciones',
            name='razon',
            field=models.CharField(default='porf', max_length=20),
            preserve_default=False,
        ),
    ]
