# Generated by Django 4.0.2 on 2022-03-04 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postgrescrud', '0005_interacciones_fecha_interacciones_hora_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interacciones',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='interacciones',
            name='hora',
        ),
        migrations.RemoveField(
            model_name='interacciones',
            name='razon',
        ),
    ]
