# Generated by Django 4.0.2 on 2022-03-04 23:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('postgrescrud', '0006_remove_interacciones_fecha_remove_interacciones_hora_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interacciones',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
