# Generated by Django 4.0.2 on 2022-03-04 23:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('postgrescrud', '0007_interacciones_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='interacciones',
            name='hora',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
