# Generated by Django 4.0.2 on 2022-03-04 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postgrescrud', '0008_interacciones_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='interacciones',
            name='razon',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
