# Generated by Django 4.0.2 on 2022-03-04 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postgrescrud', '0009_interacciones_razon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interacciones',
            name='cedula',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='oficina',
            name='cedula',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
