# Generated by Django 4.0.2 on 2022-03-04 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postgrescrud', '0010_alter_interacciones_cedula_alter_oficina_cedula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interacciones',
            name='cedula',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='oficina',
            name='cedula',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
