# Generated by Django 4.0.2 on 2022-03-05 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postgrescrud', '0011_alter_interacciones_cedula_alter_oficina_cedula'),
    ]

    operations = [
        migrations.CreateModel(
            name='contratos',
            fields=[
                ('contrato', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='oficina',
            name='contrato',
            field=models.CharField(default='si', max_length=100),
            preserve_default=False,
        ),
    ]
