# Generated by Django 4.0.2 on 2022-03-05 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('postgrescrud', '0013_rename_contrato_contratos_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oficina',
            name='contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrato', to='postgrescrud.contratos'),
        ),
    ]
