# Generated by Django 4.0.2 on 2022-03-05 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postgrescrud', '0014_alter_oficina_contrato'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratos',
            name='cantidadusuarios',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
    ]
