# Generated by Django 4.0.2 on 2022-03-05 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('postgrescrud', '0016_remove_contratos_cantidadusuarios'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contratos',
            options={'verbose_name_plural': 'Contratos'},
        ),
        migrations.AlterModelOptions(
            name='interacciones',
            options={'verbose_name_plural': 'Interacciones'},
        ),
        migrations.AlterModelOptions(
            name='oficina',
            options={'verbose_name_plural': 'Oficina'},
        ),
        migrations.AlterField(
            model_name='interacciones',
            name='cedula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cedulas', to='postgrescrud.oficina'),
        ),
        migrations.AlterField(
            model_name='oficina',
            name='contrato',
            field=models.ForeignKey(default='No existe el contrato', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='contrato', to='postgrescrud.contratos'),
        ),
    ]
