# Generated by Django 4.0.2 on 2022-03-05 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('postgrescrud', '0017_alter_contratos_options_alter_interacciones_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='usuarios',
            fields=[
                ('cedula', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrato', to='postgrescrud.contratos')),
            ],
            options={
                'verbose_name_plural': 'Oficina',
            },
        ),
        migrations.AlterField(
            model_name='interacciones',
            name='cedula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cedulas', to='postgrescrud.usuarios'),
        ),
        migrations.DeleteModel(
            name='oficina',
        ),
    ]
