# Generated by Django 4.0.2 on 2022-03-05 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postgrescrud', '0018_usuarios_alter_interacciones_cedula_delete_oficina'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuarios',
            options={'verbose_name_plural': 'Usuarios'},
        ),
    ]
