# Generated by Django 4.0.2 on 2022-03-05 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postgrescrud', '0019_alter_usuarios_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interacciones',
            name='hora',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
