# Generated by Django 4.0.2 on 2022-03-05 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postgrescrud', '0020_alter_interacciones_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interacciones',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
    ]
