# Generated by Django 4.0.2 on 2022-03-05 21:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postgrescrud', '0021_alter_interacciones_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interacciones',
            name='fecha',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='interacciones',
            name='hora',
            field=models.TimeField(default=datetime.datetime.now),
        ),
    ]
