# Generated by Django 4.0.2 on 2022-03-05 21:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postgrescrud', '0022_alter_interacciones_fecha_alter_interacciones_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interacciones',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2022, 3, 5, 17, 40, 50, 2093)),
        ),
        migrations.AlterField(
            model_name='interacciones',
            name='hora',
            field=models.TimeField(default=datetime.datetime(2022, 3, 5, 17, 40, 50, 2119)),
        ),
    ]
