# Generated by Django 4.0.2 on 2022-03-05 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('postgrescrud', '0024_alter_interacciones_fecha_alter_interacciones_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interacciones',
            name='cedula',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='postgrescrud.usuarios'),
        ),
    ]
