# Generated by Django 4.0.2 on 2022-03-05 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('postgrescrud', '0027_alter_interacciones_cedula'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interacciones',
            options={},
        ),
        migrations.AlterField(
            model_name='interacciones',
            name='cedula',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='postgrescrud.usuarios'),
        ),
    ]
