# Generated by Django 4.0.2 on 2022-03-05 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postgrescrud', '0028_alter_interacciones_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interacciones',
            options={'verbose_name_plural': 'Interacciones'},
        ),
    ]
