# Generated by Django 4.0.2 on 2022-03-05 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postgrescrud', '0032_alter_interacciones_cedula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interacciones',
            name='cedula',
            field=models.IntegerField(),
        ),
    ]
