# Generated by Django 4.0.2 on 2022-03-06 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('postgrescrud', '0034_alter_interacciones_cedula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratos',
            name='nombre',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='nombre del nuevo contrato'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrato', to='postgrescrud.contratos', verbose_name='contrato'),
        ),
    ]
