# Generated by Django 4.0.2 on 2022-03-06 00:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postgrescrud', '0036_alter_interacciones_fecha_alter_interacciones_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interacciones',
            name='fecha',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='interacciones',
            name='hora',
            field=models.TimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
