# Generated by Django 4.0.2 on 2022-03-06 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('postgrescrud', '0038_alter_interacciones_fecha_alter_interacciones_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interacciones',
            name='cedula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cedulaa', to='postgrescrud.usuarios'),
        ),
    ]
