# Generated by Django 4.0.2 on 2022-03-06 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postgrescrud', '0040_interaccione'),
    ]

    operations = [
        migrations.DeleteModel(
            name='interaccione',
        ),
    ]
