# Generated by Django 4.0.2 on 2022-03-07 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postgrescrud', '0041_delete_interaccione'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interacciones',
            name='cedula',
            field=models.IntegerField(),
        ),
    ]
