# Generated by Django 4.0.2 on 2022-03-07 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('postgrescrud', '0043_alter_interacciones_cedula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interacciones',
            name='cedula',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cedulaa', to='postgrescrud.usuarios'),
        ),
    ]
