# Generated by Django 4.0.2 on 2022-03-07 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postgrescrud', '0044_alter_interacciones_cedula'),
    ]

    operations = [
        migrations.AddField(
            model_name='interacciones',
            name='contrato',
            field=models.CharField(default='khe', max_length=100),
            preserve_default=False,
        ),
    ]
