# Generated by Django 4.0.2 on 2022-03-09 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('postgrescrud', '0046_alter_interacciones_cedula_alter_usuarios_contrato_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='diasdelasemana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Dias de la semana',
            },
        ),
        migrations.AlterField(
            model_name='horariospermitidos',
            name='dia',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='diadelasemana', to='postgrescrud.diasdelasemana'),
        ),
    ]
