# Generated by Django 4.0.2 on 2022-03-09 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postgrescrud', '0047_diasdelasemana_alter_horariospermitidos_dia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diasdelasemana',
            name='id',
        ),
        migrations.AlterField(
            model_name='diasdelasemana',
            name='dia',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
