# Generated by Django 4.0.2 on 2022-03-12 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postgrescrud', '0048_remove_diasdelasemana_id_alter_diasdelasemana_dia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interacciones',
            name='cedula',
            field=models.IntegerField(),
        ),
    ]
