# Generated by Django 4.0.2 on 2022-03-02 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pruebadb', '0003_interacciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='programador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pruebadb.empresa')),
            ],
        ),
    ]
