# Generated by Django 4.0.2 on 2022-03-03 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudpostgres', '0003_oficina_interacciones_cedula_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interacciones',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
