# Generated by Django 4.0.2 on 2022-03-04 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudpostgres', '0004_alter_interacciones_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interacciones',
            name='cedula',
            field=models.IntegerField(),
        ),
    ]
