version: '3.3'

services:

   postgres:
      image: postgres:14-alpine
      
      restart: always

      ports:
         - 44:5432
      volumes:
         - ~/Desktop/baselocal/postgresdata:/var/lib/postgresql/data
      env_file:
         - .env.postgres
   
   dbmanager:
      image: 1ab4f913f8e8
      
      restart: always
      
      volumes:
         - ~/Desktop/codigo:/app
      env_file:
         - .env.manager
         
   dbmaker:
      image: 7303efb762d9

   

   
      
   
