version: '3.3'

services:

   stream:
      
      image: ivanduque0/mjpg-streamer-raspberry:v1

      ports:
         - 8080:8080
      devices:
         - /dev/vchiq
      privileged: true
      
      restart: always

   pines:
      image: ivanduque0/pin-control-raspberry:v1

      devices:
         - /dev/gpiomem

      volumes:
         - ~/dockerpinesraspberry:/app

   pines2:
      image: ivanduque0/pin-control-raspberry:v1

      devices:
         - /dev/gpiomem

      volumes:
         - ~/dockerpinesraspberry/2:/app
