FROM navikey/raspbian-bullseye:latest

# Build mjpg_streamer
# Need to run container with the device: docker run -t -i -p 8080:8080/tcp --device=/dev/video0 image:tag
RUN apt-get update
RUN apt-get upgrade
RUN apt-get install -y git
RUN git clone https://github.com/jacksonliam/mjpg-streamer.git 

WORKDIR /mjpg-streamer/mjpg-streamer-experimental

RUN apt-get install subversion libjpeg-dev imagemagick ffmpeg cmake  -y
RUN apt-get install -y libraspberrypi0 
RUN apt-get install -y rpi-update
RUN rpi-update  -y

RUN make \ 
    && make install \
    && chmod +x docker-start.sh

EXPOSE 8080/TCP

CMD ["input_raspicam.so -x 640 -y 480 -fps 15 -ex night"]

