version: '3.3'

services:

   stream:
      image: 39d05de70dbd

      ports: 
         - 8080:8080
      devices:
         - /dev/vchiq
         
      privileged: true
      
      restart: always
   pines:
      image: e7015320686e

      devices:
         - /dev/gpiomem

      volumes:
         - ~/dockerpinesraspberry:/app                
